### PR TITLE
Update state management logic

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Refactor State management of the Drawer `open` prop so that our component will not override what the parent component passes in as `@Input`

### CODE REVIEW

**Comment by emclaug2** [comment]
> Looks good, I'll clone it down and play with it tomorrow. Does this by any chance fix the jankiness bug we were seeing when transitioning between variants too? #82

I'll add it to the list of 15 👍

**Comment by emclaug2** [comment]
That story #82 might need updated a bit; I think the Drawer jankiness is partially fixed.

**Comment by joebochill** [comment]
So I'm playing with the showcase. I start it and it loads with the (persistent) drawer open. I resize the window down and it switches to the (temporary) drawer closed. And when I resize it back up, the (persistent) drawer is closed. Shouldn't these all be open since the open prop hasn't changed?

Also seeing an error in the console:
image

**Comment by emclaug2** [comment]
I'm going to make a separate issue for the console error you're seeing above because it looks like it's stemming from the toolbar component.

**Comment by emclaug2** [comment]
This issue is fixed now - the showcase demo was manually setting the `open` state to false when transitioning from a `temporary` to `persistent` variant.

**Pull request merged**
