### PR TITLE
Bug/infolistitem light dark sb

### LINKED ISSUE #54: InfoListItem Storybook Needs Light/Dark Support
#### Describe the bug
InfoListItem in storybook does not respond well to the dark theme.

#### What is the expected behavior?
Background should not be white.

#### What are the steps to reproduce?
Go to storybook.
Open a lnfoListItem story.
Click the dark toggle.
Observe the white background in the InfoListItem.

#### What is your environment?

 Framework
- [ x] Angular
- [ ] React
- [ ] Ionic
- [ ] React Native

 Browser
- [ ] Internet Explorer
- [ ] Edge
- [ ] Safari
- [x ] Chrome
- [ ] Firefox

 Operating System
- [ ] MacOS
- [x ] Windows
- [ ] Other

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #54 

Changes proposed in this Pull Request:
- Add light dark to the InfoListItem examples

### CODE REVIEW

**Comment by huayunh** [comment]
It looks like react has similar excitements there. Logging issues now... 

image

Consider changing the icon color / avatar color to something else?

**Comment by huayunh** [comment]
Or maybe change the default color 

image

React is using gray300

**Comment by emclaug2** [comment]
Using the default color provided by the themes is a good idea; I took out the manual styling (it was Black[500] before for light/dark).  I also updated the black[500] avatar color so it stands out in both light/dark themes. 

Here's the new dark theme: 
image

**Comment by emclaug2** [comment]
Here's the light theme too: 
image

**Comment by huayunh** [comment]
So the dark info list item background is not part of the default component behavior? 

Other than that, everything looks good to me. Besides my fetish to prettier everything.

**Comment by emclaug2** [comment]
> So the dark info list item background is not part of the default component behavior?
> 
> Other than that, everything looks good to me. Besides my fetish to prettier everything.

Right now the React and Angular InfoListItem backgroundColor is inherit, so it needs to be wrapped in a div that'll update when the light/dark theme is applied.

If the InfoListItem is supposed to have a color then we'd have to bake this change into the component and not the storybook.

**Comment by huayunh** [comment]
I see, that explains. Thanks!

**Comment by huayunh** [comment]
Looks like the foreground color is not inheriting yet. I will log a separate issue on this

**Pull request merged**
