### PR TITLE
Merge latest changes into master

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Merge the latest updates into master

> published as @pxblue/angular-components@3.0.0

### CODE REVIEW

**Review by daileytj — APPROVED** [review]

**Comment by daileytj** [comment]
Do we have a good way of communicating the root class ```...-content``` updates since these would cause breaking changes for anyone using the old classes for custom styles?

**Comment by joebochill** [comment]
> Do we have a good way of communicating the root class `...-content` updates since these would cause breaking changes for anyone using the old classes for custom styles?

@evan suggested that the old classes would still work (I think). I think they'd be styling a different element, but the effect is the same?

Is it mentioned in the changelog?

**Comment by emclaug2** [comment]
There's a mention of the new host class in the changelog @joebochill  You're right that anyone using the old top-level class names to add styles will now be styling a new element, but this shouldn't matter too much.  Our older themes will style the adjusted components just fine.

**Review by emclaug2 — APPROVED** [review]

**Review by huayunh — COMMENTED** [review]
Can we change the list item tag to match what's in the DSM? Or is that for the next release?

The latest design is font size 10px, font weight 700, letter-spacing 1px, line-height 16px

**Comment by joebochill** [comment]
> Can we change the list item tag to match what's in the DSM? Or is that for the next release?
> 
> The latest design is font size 10px, font weight 700, letter-spacing 1px, line-height 16px

Next release

**Pull request merged**
