### PR TITLE
Tweak pixels for app bar story styles

### PR DESCRIPTION
**Pull request by huayunh**
## Changes proposed in this Pull Request:
- Tweaked a few pixels

## Screenshots:

Before:
image
Now: 
image

Before: 
image
Now:
image

### CODE REVIEW

**Comment by huayunh** [comment]
Not sure where this comes from. I checked all the stories and they all have their distinct names.
image

**Comment by jeffvg** [comment]
want to tweak title here....mode went away and is "with variants" ?
image

**Comment by emclaug2** [comment]
> want to tweak title here....mode went away and is "with variants" ?
> image

Yes this makes sense, the `with modes` name was before the API was updated.

**Comment by huayunh** [comment]
Updated. Please verify: https://pxb-storybook-ng-feature.web.app/

**Comment by emclaug2** [comment]
> Not sure where this comes from. I checked all the stories and they all have their distinct names.
> image

In this file, there are 2 DrawerModules defined so that the DrawerLayout stories can have an extra decorator applied.  If you remove the second README story from the 2nd module (line 115) that might fix the issue.

**Review by emclaug2 — APPROVED** [review]
Looks good to me, the warning is still there but it's not an error, just a duplicate story warning.

**Review by jeffvg — APPROVED** [review]
looks good

**Pull request merged**
