### PR TITLE
Bug/328 user menu header

### LINKED ISSUE #328: User Menu Should not be using DrawerHeader Component
#### Describe the desired behavior
Update the UserMenu component so that it's not using the DrawerHeader component.
The reason for this request is that any custom styling that applies to a DrawerHeader component could accidently be inherited by the UserMenu component.  It's not intuitive that the UserMenu shares a the DrawerHeader component with the Drawer, so there will be accidental style overrides.

#### Describe the current behavior
DrawerHeader is shared by UserMenu and Drawer; custom Drawer Header style overrides will be accidently inherited by UserMenu. 

#### Is this request related to a current issue?
No

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #328 

#### Changes proposed in this Pull Request:
- Add a UserMenuHeader component and use this in the UserMenu instead of using a DrawerHeaderComponent. 
- This will require a new themes package to work properly.

### CODE REVIEW

**Comment by daileytj** [comment]
Old full config
Screen Shot 2021-09-20 at 3 54 32 PM
Old within a toolbar
Screen Shot 2021-09-20 at 3 54 38 PM
New full config
Screen Shot 2021-09-20 at 3 54 43 PM
New within a toolbar
Screen Shot 2021-09-20 at 3 54 49 PM

Can we get the updated header to match the colors of the old one.

**Comment by emclaug2** [comment]
Yep @daileytj  I'll make a PR in the themes repo to get a new patch out so we can test this properly.

**Comment by emclaug2** [comment]
Theme fix in https://github.com/pxblue/angular-themes/pull/23

**Comment by emclaug2** [comment]
> Screen Shot 2021-09-21 at 8 08 35 AM
> The items in the dropdown aren't full width so we end up with a strange view on hover.

Fortunately this is a storybook demo issue; the width of the nav list was set to 12em, I've removed the width and it looks fine now.

**Comment by huayunh** [comment]
> > Screen Shot 2021-09-21 at 8 08 35 AM
> > The items in the dropdown aren't full width so we end up with a strange view on hover.
> 
> Fortunately this is a storybook demo issue; the width of the nav list was set to 12em, I've removed the width and it looks fine now.

Looks like it still persist in the link you sent above

**Comment by huayunh** [comment]
Everything else looks good style-wise

**Comment by emclaug2** [comment]
> Everything else looks good style-wise

Hoping this is a cache issue because it looks good on my end; try in incognito?

**Comment by huayunh** [comment]
Looking good

**Review by daileytj — APPROVED** [review]
That's what I'm talking about! Looks good!

**Pull request merged**
