### PR TITLE
Add empty state playground

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
-  Add Playground for Empty State

### CODE REVIEW

**Comment by huayunh** [comment]
Am I looking at only the playground? It looks like you've got the examples and API docs working as well

**Comment by huayunh** [comment]
# 1 
Examples page, typo 
image

# 2

Is it possible to style that accordion header closer to this in our Angular theme package? Or would we be controlling the style too much?

image

# 3

No complaints to the other two pages

**Review by daileytj — APPROVED** [review]
Looks good to me. Just wondering if we should have some options to toggle the icon since it is required and to demonstrate what a different icon may look in the code snippet.

**Comment by emclaug2** [comment]
@huayunh Is the mat-accordion header support to be blue[500] in our theme?  Sounds like a +1 theme issue.

**Comment by emclaug2** [comment]
> @huayunh Is the mat-accordion header support to be blue[500] in our theme? Sounds like a +1 theme issue.

I'll bring this up in the demo.

**Pull request merged**
