### PR TITLE
Feature/112 host class

### LINKED ISSUE #111: Follow the Angular Material class naming paradigm
#### Describe the desired behavior
Host elements for our components should have a class attached to them. For example, observe the `<mat-list-item>` component from angular material has a class `.mat-list-item`. The first rendered element has a class of `.mat-list-item-content`

#### Describe the current behavior
We are currently applying the `.pxb-*` class to the first element (not the host).

#### Is this request related to a current issue?
This was found as part of the drag/drop issue we uncovered with the sortable list design pattern example. It's also related to #112.

#### Additional Context
We can set classes on the host element using the following syntax in the Component decorator:
```
host: {
    'class': 'pxb-info-list-item-test',
},
```

### LINKED ISSUE #112: Components should set display rule for first rendered elements
#### Describe the bug
The first element in our component DOM trees do not always set a display type. This can cause unexpected behavior when trying to style certain components. This is a known issue in the InfoListItem, but we should verify the other components as well.

#### What is the expected behavior?
First element in component trees should explicitly set the desired display type.

#### Anything else to add?
When the browser doesn't recognize a HTML tag (such as for custom components), it renders them with display:inline by default (with height/width of 0 and certain CSS rules having no effect). When the first element in the DOM of a component is also an unrecognized browser tag (such as `<mat-list-item>`), that seems to be when the issues arise - we just need to make sure these root elements have an explicit display type.
Do this with #111

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #112, Fixes #111 

#### Changes proposed in this Pull Request:
- Top-level components have a class applied to the host element
-  Docs updated

UserMenu has no root-class, so it has no `pxb-user-menu-content` class.

These components are internal to the Drawer; I didn't apply a `display: flex` to them since they work fine already and shouldn't be used outside of the Drawer. 
- DrawerHeader
- DrawerSubheader
- DrawerBody
- DrawerNavItem
- DrawerNavGroup
- DrawerFooter

### CODE REVIEW

**Comment by emclaug2** [comment]
Themes are backwards-compatible; no changes needed.

**Comment by joebochill** [comment]
> Themes are backwards-compatible; no changes needed.

Really? That's nice.

**Comment by emclaug2** [comment]
> > Themes are backwards-compatible; no changes needed.
> 
> Really? That's nice.

Yep; our themes are just using css with the parent class of each component already assumed to be `pxb-[component-name]`, so this refactor works pretty nicely.  

The only issue that I've noticed is that when I changed the host element of the DrawerLayout to be flex, the body of the showcase app needed to specify a height in order to work.   This is a bit annoying.

**Comment by huayunh** [comment]
Changelog?

**Comment by huayunh** [comment]
code looks all good

**Review by joebochill — COMMENTED** [review]
Looks good. 

This is still a breaking change though even though the themes are backward compatible right? Should we update the changelog to be 3.0.0?

Also, we probably want to set the root display for the ILI to block instead of flex, or the scorecard footers look goofy:
image

**Comment by emclaug2** [comment]
> Looks good.
> 
> This is still a breaking change though even though the themes are backward compatible right? Should we update the changelog to be 3.0.0?
> 
> Also, we probably want to set the root display for the ILI to block instead of flex, or the scorecard footers look goofy:
> image

This stuck out to me too but turns out the showcase has some styles that are overriding the default behavior of the scorecard's InfolistItem.    I just opened a PR to update the showcase here: https://github.com/pxblue/angular-showcase-demo/pull/2

**Comment by joebochill** [comment]
> This is still a breaking change though even though the themes are backward compatible right? Should we update the changelog to be 3.0.0?

**Review by joebochill — APPROVED** [review]

**Pull request merged**
