### PR TITLE
Bug/sb drawer expansion panel

### PR DESCRIPTION
**Pull request by emclaug2**
Changes proposed in this Pull Request:
- Fix bug where the expansion panel in the Drawer `with subheader` story wouldn't expand.

### CODE REVIEW

**Comment by jeffvg** [comment]
I see the same behavior clicking accordion. Toggle only happens after clicking and moving pointer of click area.

ng-drawer-subheader

**Comment by emclaug2** [comment]
You're right @jeffvg .  On Friday the accordion was working just fine for me but I see what you're saying; it's unresponsive until the mouse is moved outside of the container.  I'll take another look at this later in the day; definitely some strange behavior here.

**Comment by huayunh** [comment]
That accordion subheader looks like a card from Jeff's screenshot...

**Comment by emclaug2** [comment]
A little more information about this bug.   I think storybook is having some change detection issues when a component is conditionally rendered.  If you open the subheader demo with the accordion rendered by default, it'll work as expanded.  Open/close on click.  

https://pxblue-components.github.io/angular-dev/?path=/story/components-drawer--with-subheader&knob-divider=true&knob-Subheader Content=Accordion

If you toggle to `filter` then back to `accordion` using the knobs the open/close functionality is broken again.

**Comment by emclaug2** [comment]
> That accordion subheader looks like a card from Jeff's screenshot...

I've replaced the accordion with a card to make things simpler.

**Comment by emclaug2** [comment]
Forgot to Prettier & Lint! Should be good to go now.

**Pull request merged**
