### PR TITLE
Merge 3.0.1 fixes to Master

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Updates the ListItemTag styles to match our DSM recommendations.
- Fixes a bug in the InfoListItem where the dividers were not probably showing.
- Fixes a bug in the ListItemTag where it would span 100% width of non-flex containers.

I should have waited for this PR to get merged to master before making the tag.
https://github.com/pxblue/angular-component-library/releases/tag/v3.0.1

### CODE REVIEW

**Comment by huayunh** [comment]
image

overall height: 16px

font-size: 10px

**Comment by emclaug2** [comment]
> image
> 
> overall height: 16px
> 
> font-size: 10px

This is so strange, the local dev branch has the ListItemTag be 16px high with a font-size of 10px.   I'm trying to figure out now why the changes didn't get deployed to the dev site.

**Comment by huayunh** [comment]
Now it looks correct

**Comment by huayunh** [comment]
Remember to update the change log before you publish

**Comment by emclaug2** [comment]
> Now it looks correct

This was a hiccup with circleci, everything looked fine in the previous build's logs.  Maybe because I merged multiple PRs in dev at once.

**Review by huayunh — APPROVED** [review]

**Comment by emclaug2** [comment]
Just a reminder to myself:  The tag is applied after the master (or release/x.x.x) merge.  
This'll be the second time deleting the 3.0.1 tag.  👎

**Review by joebochill — APPROVED** [review]

**Pull request merged**
