### PR TITLE
Feature/subtitle

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Add the Drawer header Angular subtitle to match figma designs here: https://www.figma.com/file/hOk7yEWOdZPbGTF6kze1sO/Dev-Doc?node-id=0%3A1

### CODE REVIEW

**Comment by huayunh** [comment]
1. Is there a separate story to update our dev doc home page & favicons as well?
2. depending on how pixel-perfect you are looking to get, consider taking a screenshot, pasting it right next to the Figma design to do a side-by-side comparison

**Comment by emclaug2** [comment]
> 1. Is there a separate story to update our dev doc home page & favicons as well?
> 2. depending on how pixel-perfect you are looking to get, consider taking a screenshot, pasting it right next to the Figma design to do a side-by-side comparison

This is specifically just for the Drawer Header.  There's a much larger story in-progress now that covers _everything else_, besides examples-page verbiage.

**Comment by huayunh** [comment]
@ektasawant As long as the height of the drawer header is matching that of the app bar, I am happy with it. I believe the default for Angular Material and Material UI is 56px tall for mobiles, and 64px tall for tablets and above

**Review by jeffvg — APPROVED** [review]
nice looks good

**Pull request merged**
