### PR TITLE
Update drawer font size

### PR DESCRIPTION
**Pull request by daileytj**
Fixes Themes 71.

Changes proposed in this Pull Request:
- Update drawer font size to 14px

### CODE REVIEW

**Comment by emclaug2** [comment]
Font size looks good to me.

One thing I noticed is that the font size of the selected story is still 13px.   

image

Is this supposed to be 14?

**Comment by joebochill** [comment]
Is this not something that we can fix in the storybook theme?

**Comment by jeffvg** [comment]
Another one off with a read me, still 13

font-ng

**Comment by jeffvg** [comment]
same warning as the react comp lib too

Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
    in Unknown (created by Context.Consumer)
    in WithTheme(Component)
    in WithTheme(Component) (created by Preview)
    in div (created by Context.Consumer)
    in Side (created by FlexBar)
    in div (created by Context.Consumer)
    in Styled(div) (created by FlexBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in SimpleBar
    in Unknown (created by Context.Consumer)
    in Styled(Component) (created by ScrollArea)
    in ScrollArea
    in Unknown (created by Context.Consumer)
    in Bar (created by FlexBar)
    in div (created by Flex

**Comment by daileytj** [comment]
> Is this not something that we can fix in the storybook theme?

Nope. Unfortunately, the theme config for storybook is fairly limited.

**Comment by joebochill** [comment]
@jeffvg if it works in the dev branch, I would log those as a separate issue from this one for the font size.

**Pull request merged**
